/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  version: string;
  channel: Channel;
  items: Item[];
  [k: string]: unknown;
}
export interface Channel {
  required?: unknown;
  title?: string;
  [k: string]: unknown;
}
export interface Item {
  required?: unknown;
  title?: string;
  published?: string;
  explicit?: boolean;
  [k: string]: unknown;
}
